### ISSUE TITLE
Trouble when requesting many shards

### ISSUE THREAD

**Issue by kimjunsung04** [RafaelSolVargas/Vulkan#35] opened 2023-02-08 16:55 UTC
Hello, to use the Vulkan music bot
When I tried to run it, I ran into a problem.

Looking around the code https://github.com/RafaelSolVargas/Vulkan/blob/f4e9e46d6d008d924baeec4a255233e86e76a216/Parallelism/PlayerProcess.py#L369 in that line
I have confirmed that it creates a new instance.
This action is the process of creating a player process when playing a song on a new server.
A problem occurred in that part.

Bots that require a lot of shards take a long time to load in the beginning.
In the same way, it takes a lot of time to create instants, so songs cannot be played, and many servers are experiencing bottlenecks in creating instants when requesting song playback.

As a result, the song cannot be played.

Is there any way to solve that problem?
There are so many cool features that I really want to try!
Any help would be appreciated!

**Comment by RafaelSolVargas** [comment] 2023-02-08 20:09
Hello!
Yes, this piece of code starts a new python process that will only be used to play music on a specific server, but to be honest, I didn't thought that many processes could start delaying the instantiation, so help me with some information.

How many servers/bot instances are will trying to execute before this delay starts to apper?
What do you mean by a bot that required too many shards?

```As a result, the song cannot be played.```
Is there a error being throwed in this situation? If yes, can you show me a screenshot?

**Comment by kimjunsung04** [comment] 2023-02-09 00:39
How many servers/bot instances are will trying to execute before this delay starts to apper?
- The bot I tested has about 36,000 participating servers.
- The number of instances is one.
I think it is one because the delay started while creating an instance when the play command was used immediately after loading the bot.
- My bot had 37 shards.

What do you mean by a bot that required too many shards?
- I'm not good at English, so I think I used the wrong expression.
Bots with about 5 shards are likely to have the same problem.

As a result, the song cannot be played.
Is there a error being throwed in this situation? If yes, can you show me a screenshot?
- As shown in the screenshot below, the message 'NoneType' object has no attribute 'connect' is displayed.
The cause of this is identified as a problem with trying to connect before the instant load is complete.
However, I don't think waiting for instant load to complete is a solution to the problem.

![image](https://user-images.githubusercontent.com/70435510/217683996-52a03c50-27d8-48f4-9b69-505808e2fbd9.png)

**Comment by RafaelSolVargas** [comment] 2023-02-09 02:36
- My bot had 37 shards.
Actually i didn't knew what is a shard, but then i look up and found this [link](https://www.reddit.com/r/Discord_Bots/comments/ozzk0h/what_is_a_shard_an_explanation/) and now i think that i get what you are saying.

Well, first of all, the whole Vulkan revolves around multiprocessing and having a Python process just to play the music, so that the music playback doesn't soffer when many requets come from Discord.
But for that, i needed to create a new instance of the bot itself, so this function came about

https://github.com/RafaelSolVargas/Vulkan/blob/f4e9e46d6d008d924baeec4a255233e86e76a216/Parallelism/PlayerProcess.py#L369-L372

For bots without shards the connection was always established before the VCommandsType.Play got to the Player Process and it always worked, but in your case it's not working. A simple solution that could "fix" this, is to put some sort of wait on line 260 below and wait for the bot connection to establish.

https://github.com/RafaelSolVargas/Vulkan/blob/f4e9e46d6d008d924baeec4a255233e86e76a216/Parallelism/PlayerProcess.py#L259-L263

I have already patched this in this [commit](https://github.com/RafaelSolVargas/Vulkan/commit/8dc68b089839820ea7006f712cc3f398bdf1d9b7)

But as you pointed out, it's not a real fix because there might be a huge delay to create this instance. However, any other solution would completely change the way Vulkan handles multiprocessing, and that takes a fair amount of time and effort.
If possible, try this solution and see if this fix is ​​working for you, let me know any updates!

Thanks for reporting this issue! :)

**Comment by kimjunsung04** [comment] 2023-02-09 03:13
Thank you for your kind reply!
As expected, the problem of not playing is solved, but it seems that it will take some time to load.
However, since it is executed once per server, I think that it can be used to some extent if the uptime is maintained well!
I'll leave a reply after checking if it worked.
thank you!

**Comment by kimjunsung04** [comment] 2023-02-10 04:46
As a result, it was not effective for me.
It took about 5 minutes to bring in sharding, so I thought it was too much.

I'm looking at the following two things in different ways.
- Bring only certain shards
- Replication of the main process

I will continue to find a way and I will inform you if you find a solution.
If you know how to solve it, you would be grateful if you share it.
Thank you for your help!

**Comment by RafaelSolVargas** [comment] 2023-02-18 18:01
In the following days I'll work in a Vulkan version to allow you to choose when the Bot should start a new process to play the song or when it should start the song playback in the same process, which will fix your delay problem.

**Comment by RafaelSolVargas** [comment] 2023-02-20 05:11
Hello!
As a result of many hours of work, I patched this in this PR https://github.com/RafaelSolVargas/Vulkan/pull/37, take a look of what has changed and how to set up the project for your usage.
Thanks for the report! 
If you had any questions, just let me know!

**Comment by kimjunsung04** [comment] 2023-02-21 04:36
Oh! Thank you!
I tried the updated code right away.
However, a connection-related error occurred.
```
[ERROR CONNECTING TO VC] -> 'NoneType' object has no attribute 'connect'
[ERROR IN PLAY SONG FUNCTION] -> 'NoneType' object has no attribute 'is_connected', <class 'AttributeError'>
```
As a result, the following error occurred.
I modified the int and tried many things, but it didn't work for me.
Thank you for trying!🥹

**Comment by RafaelSolVargas** [comment] 2023-02-21 22:40
I think this error is related to the first error you reported.
The error happens because the Bot is still loading and I used a function that retrieves the voiceChannel and this function returned None, which was an unexpected behavior.
I tried to fix that in this comit https://github.com/RafaelSolVargas/Vulkan/commit/97996a1647b36738f6868f6061bf392010c42d2f. 
Please check if everything is alright.

**Comment by RafaelSolVargas** [comment] 2023-02-22 22:16
Are you sure that you have the latest bot version? And if you set up the attribute SONG_PLAYBACK_IN_SEPARATE_PROCESS to False as was described in the [Settings page](https://github.com/RafaelSolVargas/Vulkan/blob/master/.github/Docs/SETTINGS.md)?

Because the function that are throwing this error is that:
![image](https://user-images.githubusercontent.com/86136313/220769703-8dc72e76-0e66-4613-ba55-e6bffa62757a.png)

If you take a look in the line 338 the execution will not pass this part until the property ```self.__voiceChannel``` is different from None, and the error you are reporting right now tells that 'NoneType' object has no attribute 'connect', so, I think that you are not using the correct version.

**Comment by RafaelSolVargas** [comment] 2023-02-27 12:37
Thanks for your time and tries, @kimjunsung04.
I'm closing this issue for now, but you can come back and report any issue at any time!

**Closed by RafaelSolVargas** 2023-02-27 12:37 UTC
